// Proof of concept: read the saved LCSC fixtures and write docs/lcsc-poc-report.md
// (coverage, categories, and the parameter labels LCSC uses per category).
// Run: node scripts/poc-lcsc/report.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const DIR = 'tests/fixtures/lcsc-detail';
const parts = readdirSync(DIR).filter((f) => f.endsWith('.json')).map((f) => JSON.parse(readFileSync(`${DIR}/${f}`, 'utf8')));
const ok = parts.filter((p) => p.status === 'ok');
const missing = parts.filter((p) => p.status !== 'ok');

const byCat = new Map();
for (const p of ok) {
  const key = `${p.parentCatalog} / ${p.catalog}`;
  if (!byCat.has(key)) byCat.set(key, []);
  byCat.get(key).push(p);
}

let md = `# LCSC proof of concept: what the labelled parameters look like\n\nGenerated by \`scripts/poc-lcsc/report.mjs\` from \`${DIR}\` (${parts.length} parts fetched ${parts[0]?.fetchedAt?.slice(0, 10)}).\n\n`;
md += `## Coverage\n\n- ${ok.length} of ${parts.length} parts returned data.\n- Not listed by LCSC: ${missing.map((m) => m.productCode).join(', ') || 'none'}.\n`;
md += `- Parts with at least one parameter: ${ok.filter((p) => p.params.length).length}.\n- Parts where a parameter has LCSC's own numeric value: ${ok.filter((p) => p.params.some((x) => x.number !== null && x.number !== -1)).length}.\n\n`;
md += `## Categories (LCSC's own)\n\n| Category | Parts | Example MPNs |\n|---|---|---|\n`;
for (const [k, v] of [...byCat].sort((a, b) => b[1].length - a[1].length)) md += `| ${k} | ${v.length} | ${v.slice(0, 3).map((p) => p.productModel).join(', ')} |\n`;
md += `\n## Parameter labels per category\n\n"Num" = how often LCSC also supplies its own normalised number (a validation oracle).\n`;
for (const [k, v] of [...byCat].sort((a, b) => b[1].length - a[1].length)) {
  const labels = new Map();
  for (const p of v) for (const x of p.params) {
    const e = labels.get(x.name) ?? { n: 0, num: 0, ex: new Set() };
    e.n++; if (x.number !== null && x.number !== -1) e.num++; if (e.ex.size < 3) e.ex.add(x.value);
    labels.set(x.name, e);
  }
  md += `\n### ${k} (${v.length} parts)\n\n| Label | Parts | Num | Examples |\n|---|---|---|---|\n`;
  for (const [name, e] of [...labels].sort((a, b) => b[1].n - a[1].n)) md += `| ${name} | ${e.n} | ${e.num} | ${[...e.ex].join(' ; ')} |\n`;
}
writeFileSync('docs/lcsc-poc-report.md', md);
console.log(md.split('\n').slice(0, 60).join('\n'));
